setwd("C:/Users/Rohit/Desktop/Data Science/Coursera/Exploratory Data Analysis")
energy <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
energy$Date = as.Date(as.character(energy$Date), format = "%d/%m/%Y")
library(chron)
energy$Time = chron(times. = energy$Time, format = "h:m:s")
my_data = subset(energy, Date == "2007-02-01" | Date == "2007-02-02")
my_data$Global_active_power = as.numeric(as.character(my_data$Global_active_power))
plot(x = my_data$Time[order(my_data$Time)], y = my_data$Global_active_power, type = "l", xaxt = 'n', xlab = "", ylab = "Global Active Power (kilowatts)")
axis(1, at = c(0.0, 0.5, 1), labels = c("Thu", "Fri", "Sat"))
dev.copy(png, "plot2.png", height = 480, width = 480, units = "px")
dev.off()
